version: '3'
services:
  backend:
    container_name: mjsoap-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: yarn start
    ports:
      - 27007:7000
