version: '3'
services:
  backend:
    container_name: mjsoap-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLIENT_URL="http://10.38.51.191:27002"
    restart: always
    entrypoint: yarn start
    ports:
      - 27001:7000
